### ISSUE TITLE
cloning cloudmesh results in problem

### ISSUE THREAD

**Issue by badmutex** [cloudmesh/get#11]
Recent changes to cloudmesh break curl install.

```
+ cd cloudmesh
+ git pull
Already up-to-date.
+ ./install new --force

# ######################################################################
# new --force
# ######################################################################
ERROR: Your environment may not be properly configured.
       Have you run the following command?

         install system

'module' object has no attribute 'dir'
Traceback (most recent call last):
  File "./install", line 154, in main
    from cloudmesh_install.install import install_command
  File "/home/ubuntu/cloudmesh/cloudmesh_install/install.py", line 39, in <module>
    print sys.dir()
AttributeError: 'module' object has no attribute 'dir'
```

**Comment by badi** [comment]
cloudmesh 9494711

**Comment by badmutex** [comment]
`pip uninstall cloudmesh{,_base}`
`pip install -U`

```
cloudmesh_base==2.5.15
cloudmesh==2.3.1
```

`checkout cloudmesh 0022179a3eab180642482bd8001293e0a1d04576`
